### ISSUE TITLE
How To Add a Header and other tool bar elements.

### ISSUE THREAD

**Issue by balsimpson** [wantpinow/nuxt-editorjs#2]
I was able to install it and use it without a problem, but I can't find any documentation on how to add Header and other toolbar elements.

**Comment by wantpinow** [comment]
Hi @balsimpson thanks for the heads up. I've just added the Header and List tools to the latest version (`1.0.4`). I'll continue adding more common tools as time goes on.

As for custom modules I haven't looked too much into it but it should be doable via some module config options. If you have any suggestions or want to contribute, feel free to clone and send a pull request.

Cheers!
